### PR TITLE
Implement fixable check

### PR DESCRIPTION
**Pull request by indykoning**
I've changed the code up to do a "Dry Run" first and point out all errors.
Using the FixableProcessResultProvider we can promt the user wether they want us to automatically fix it or not.

These changes also automatically add a message asking to review the changes made by pint
image

That screenshot is what is shown when automatic fixing is not enabled,
Otherwise the prompt asking wether to fix the changes is not shown, only the warning to review the changes and commit again.

This pulls the functionality more inline with composer_normalize and phpcs_checker.

However i can understand that what you have currently is how you intend it to use it, thus i leave wether you want to merge this or not up to you.

### CODE REVIEW

**Comment by JamesHemery** [comment]
Hi @indykoning,

Thanks for your PR !

I think it's a good thing, but this way it drastically changes the current behavior.

With these changes, the files are no longer staged (git add) after the fix. This can be annoying in case of automatic fix during commits because you'll have to make a new a commit.

What do you think about adding an option `auto_git_stage` to keep this behavior ?

**Comment by indykoning** [comment]
Yeah i think that'd be a good way to give people the choice between the 2 different ways of working. I'll work it in!

I will note though that if grumphp finds issues and auto fixes it it will actually prevent the commit from happening e.g. what happens with this change:

I've made a change to the routes/web:
image

I commit the file and let grumphp run
image
Pint mentions the failed style check with a diff of what should've been changed
image

It would ask you wether to fix it automatically (which i've set up to always say yes https://github.com/phpro/grumphp/blob/master/doc/parameters.md#:~:text=fixer.fix_by_default):
image

It cancels the commit and now i have the routes/web.php staged and unstaged
image

The unstaged file is the one with all the automatic fixes, so you can manually review them first with a `git diff routes/web.php` which excludes your changes (because it's staged) and only includes the automatic fixes.

If you're happy with it you can `git add routes/web.php` and commit again.
image
image

Only once grumphp runs successfully it will actually do the commit

**Comment by indykoning** [comment]
The `auto_git_stage` flag has been added so now we're able to toggle between functionalities 🚀 
I've also added the option to [ignore_patterns](https://github.com/phpro/grumphp/blob/master/doc/tasks/phpcs.md#:~:text=This%20is%20a%20list%20of%20patterns%20that%20will%20be%20ignored%20by%20phpcs.%20With%20this%20option%20you%20can%20skip%20files%20like%20tests.%20Leave%20this%20option%20blank%20to%20run%20phpcs%20for%20every%20php%20file.) which is a pretty powerful function to exclude specific files or folders depending on a pattern, in case a specific file or folder causes trouble (like tests, public, etc.)

**Comment by JamesHemery** [comment]
Hi @indykoning, sorry, I completely forgot about this PR! 

I've reworked your implementation to better match our wishes.

In PR #3 I introduce two new configuration variables `auto_fix` and `auto_stage` which are by default configured to be activated in pre_commit. I've also copied your configuration variables `preset` and `ignore_patterns`.

**Comment by JamesHemery** [comment]
Released in 0.0.2, thanks for your work !

**Pull request closed without merging**
